from typing import Protocol, List, Dict, Any, Optional

class BaseRepository(Protocol):
    def read_data(self) -> Dict[str, Any]:
        ...
    
    def write_data(self, data: Dict[str, Any]) -> None:
        ...

    def get_products(self) -> List[Dict[str, Any]]:
        ...

    def add_product(self, nome: str, descricao: str, preco: float, estoque: int, categoria: str, detalhes: Optional[Dict[str, Any]] = None) -> Optional[str]:
        ...

    def update_product(self, product_id: str, dados: Dict[str, Any]) -> bool:
        ...

    def update_product_stock(self, product_id: str, novo_estoque: int) -> None:
        ...

    def delete_product(self, produto_id: str) -> None:
        ...

    def listen_to_orders(self, callback):
        ...

    def get_orders(self) -> List[Dict[str, Any]]:
        ...

    def get_coupons(self) -> List[Dict[str, Any]]:
        ...

    def create_local_order(self, order: Dict[str, Any]) -> Dict[str, Any]:
        ...

    def update_order_status(self, pedido_id: str, novo_status: str) -> None:
        ...

    def get_movements(self) -> List[Dict[str, Any]]:
        ...

    def add_movement(self, movement: Dict[str, Any]) -> None:
        ...
